# Generated by Django 5.0.9 on 2024-09-20 08:22

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Use in jupyter notebooks'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
