# Generated by Django 5.0.9 on 2024-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_can_delete_alter_blogpost_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
